spring:
  profiles:
    active: dev
---
spring:
  profiles: dev

recPath: src\main\resources\rec\rec.txt
starterPath: src\main\resources\starter\starter.yml
taskPath: src\main\resources\task\task.yml
---
spring:
  profiles: pro

recPath: .\rec\rec.txt
starterPath: .\starter\starter.yml
taskPath: .\task\task.yml
---
spring:
  profiles: test
